name: CI Pipeline for MR ZERO Scanner

on:
  push:
    branches:
      - main  # Jalankan pipeline saat ada push ke branch main
  pull_request:
    branches:
      - main  # Jalankan pipeline saat ada pull request ke branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Gunakan runner Ubuntu terbaru

    steps:
      # Langkah 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versi Python yang digunakan

      # Langkah 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Langkah 4: Jalankan linting (opsional)
      - name: Lint code
        run: |
          pip install flake8
          flake8 src/ --count --show-source --statistics

      # Langkah 5: Jalankan unit tests (jika ada)
      - name: Run tests
        run: |
          pytest src/tests/  # Jika ada folder tests dengan file unit test

      # Langkah 6: Build artifact (opsional)
      - name: Build artifact
        run: |
          pyinstaller --onefile src/scanner.py  # Jika ingin membuat executable